apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-v3io-config
  labels:
    app: {{ template "shell.name" . }}
    chart: {{ template "shell.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ include "v3io-configs.java.configMap" . | indent 2 }}

  health_check.sh: |
{{ include "v3io-configs.script.javaHealthCheck" . | indent 4 }}
    # Test that dayman is alive and accessible
    cd /tmp && V3IO_PASSWORD= java -cp ${IGUAZIO_JAVA}/libs/scala-library-${SCALA_VERSION}.jar:${IGUAZIO_JAVA}/libs/v3io-hcfs_${SCALA_MAJOR_VERSION}-${IGUAZIO_VERSION}.jar io.iguaz.v3io.daemon.CheckHealth

