apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "spark.master-name" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: spark-master
data:
  health_check.sh: |
{{ include "v3io-configs.script.httpHealthCheckWithJava" . | indent 4 }}
    # Test that dayman is alive and accessible
    cd /tmp && V3IO_PASSWORD= java -cp ${IGUAZIO_JAVA}/libs/scala-library-${SCALA_VERSION}.jar:${IGUAZIO_JAVA}/libs/v3io-hcfs_${SCALA_MAJOR_VERSION}-${IGUAZIO_VERSION}.jar io.iguaz.v3io.daemon.CheckHealth

  run.sh: |
    #!/usr/bin/env bash
    set -e

    /spark-master \
      --service-port={{ .Values.master.servicePort }} \
      --webui-port={{ .Values.master.webAdmin.servicePort }} \
      --master-hostname={{ template "spark.master-name" . }}
